# Generated by Django 5.0.6 on 2024-09-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='miqdori',
        ),
    ]
