# Generated by Django 5.0.6 on 2024-09-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_rename_quantity_order_miqdori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='miqdori',
            new_name='quantity',
        ),
    ]
